### ISSUE TITLE
伊利系列里的金典  999 还有特步  三个跑不起来

### ISSUE THREAD

**Issue by yaozailiming** [CHERWING/CHERWIN_SCRIPTS#25]
====== 获取用户信息 ======
获取用户信息成功！✅
Traceback (most recent call last):
  File "/ql/data/scripts/伊利甄稀金典.py", line 307, in <module>
    run_result = RUN(infos, index).main()
  File "/ql/data/scripts/伊利甄稀金典.py", line 187, in main
    if self.get_user_info():
  File "/ql/data/scripts/伊利甄稀金典.py", line 110, in get_user_info
    siteName = site[registerSource]
KeyError: '1130'

**Comment by yang7758258** [comment]
+1 
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/43715693/76c43dbe-ade4-4f3f-9f1a-9f87a84f4b79)
也是跑到这个就报错

**Comment by CHERWING** [comment]
已更新伊利系列，原[金典SATINE]改名[金典有机生活+]registerSource改成了1130

**Comment by CHERWING** [comment]
999屏蔽了服务器ip需要用家宽跑，特步测试正常请确认抓的参数是否正确

**Comment by yaozailiming** [comment]
> 已更新伊利系列，原[金典SATINE]改名[金典有机生活+]registerSource改成了1130
 把ck输入脚本跑起来了一次  然后又跑不起来了  报错如下 Traceback (most recent call last):
  File "/ql/data/scripts/特步.py", line 263, in <module>
    run_result = RUN(infos, index).main()
  File "/ql/data/scripts/特步.py", line 41, in __init__
    self.token = json.loads(split_info[0])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by CHERWING** [comment]
> > 已更新伊利系列，原[金典SATINE]改名[金典有机生活+]registerSource改成了1130 把ck输入脚本跑起来了一次 然后又跑不起来了 报错如下 Traceback （the recent call last）： 文件“/ql/data/scripts/特步.py”，第 263 行，在  run_result = RUN（infos， index）.main（） 文件“/ql/data/scripts/特步.py”，第 41 行，**init** self.token = json.loads（split_info[0]） 文件“/usr/lib/python3.10/json/**init**.py”，第 346 行，在 loads 中返回 _default_decoder.decode（s）文件“/usr/lib/python3.10/json/decoder.py”，第 337 行，解码 obj，end = self.raw_decode（s， idx=_w（s， 0）.end（）） 文件“/usr/lib/python3.10/json/decoder.py”，第 353 行，在 obj raw_decode中，end = self.scan_once（s， idx） json.decoder.JSONDecodeError：期望属性名称括在双引号中：第 1 行第 2 列 （char 1）

还是ck问题，确保ck为json格式
