### ISSUE TITLE
天翼云盘报错

### ISSUE THREAD

**Issue by L2c95** [CHERWING/CHERWIN_SCRIPTS#45]
运行日志如下：

Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/TYYP.py", line 12, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'

**Comment by L2c95** [comment]
劲友家小程序报错，日志：
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JYJ.py", line 13, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by klcb2010** [comment]
看日志啊 这么明显了

**Comment by L2c95** [comment]
> 看日志啊 这么明显了

依赖装上就好了，谢谢
