### ISSUE TITLE
PPCS组队失败

### ISSUE THREAD

**Issue by johnzon520** [CHERWING/CHERWIN_SCRIPTS#61]
---------开始执行第1个账号>>>>>
>>>>>>开始随机选择位置
>选取随机地点成功
--------签到组队--------
>>>>>>第1个账号开始助力作者
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/PPCS.py", line 676, in <module>
    RUN(infos, index).help()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/PPCS.py", line 567, in help
    self.joinAuthorTeam()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/PPCS.py", line 406, in joinAuthorTeam
    if code.get('status',False) and code.get('phone','') != self.phone:
AttributeError: 'RUN' object has no attribute 'phone'

## 执行结束... 2024-07-10 09:00:11  耗时 10 秒

**Comment by idiomer** [comment]
@johnzon520  请教下大佬，朴朴的refresh_token怎么获取？抓朴朴小程序现在好像只能抓到access_token

**Comment by johnzon520** [comment]
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/7636474c-34b6-4b6c-bafc-e42c8c5d13b0)

**Comment by idiomer** [comment]
> ![image](https://private-user-images.githubusercontent.com/46586257/347645312-7636474c-34b6-4b6c-bafc-e42c8c5d13b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjMzNTAsIm5iZiI6MTcyMDY2MzA1MCwicGF0aCI6Ii80NjU4NjI1Ny8zNDc2NDUzMTItNzYzNjQ3NGMtMzRiNi00YjZjLWJhZmMtZTQyYzhjNWQxM2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAxNTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMTk0M2M5MDg0ODE2ZTI2ZDE1MGZmNzU5ZTVhNTU5NWE5YWJhODQyN2M4OTljMzQyZDZkY2ExZjY2ZjM0ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QCyEQHZ1VlrTtz6yFFF586aFEizW7HXdFX296AmMIkg)

------------
新版本的app和小程序都没这个接口了，降级可

**Comment by 43984927** [comment]
修改44行，加入phone=None，self.phone = phone
/
class RUN:
    def __init__(self,info,index,access_token=None,user_id=None,phone=None):
        global one_msg
        self.phone = phone
![360截图20240715172837247](https://github.com/user-attachments/assets/146da6e4-a89e-4164-85aa-6064fe6d358a)
