### ISSUE TITLE
顺丰速运不能运行

### ISSUE THREAD

**Issue by 2536** [CHERWING/CHERWIN_SCRIPTS#78]
--------开始执行第1个账号>>>>>
用户:【15****81】登陆成功
>>>>>>开始执行签到
今日已签到，本周累计签到【2】天
>>>>>>超值福利签到
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 1750, in <module>
    run_result = RUN(infos, index).main()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 1594, in main
    self.superWelfare_receiveRedPacket()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 172, in superWelfare_receiveRedPacket
    gift_names = ', '.join([gift['giftName'] for gift in gift_list])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by drw2005** [comment]
是的，同样的问题。

另外，现在顺丰抓包好像抓不到这个https://mcs-mimp-web.sf-express.com/mcs-mimp/share/app/shareRedirect
兄弟用什么抓包的？

**Comment by Canary233** [comment]
同样的问题

**Comment by Canary233** [comment]
怎么close了？解决了吗

**Comment by drw2005** [comment]
问题并没有解决

**Comment by 521141** [comment]
@2536 把超值福利签到的任务给注释掉，我没找到入口，没法抓包
