### ISSUE TITLE
顺丰脚本报错 辛苦作者有空指导下是不是哪里设置错误 谢谢

### ISSUE THREAD

**Issue by Cyber-H** [CHERWING/CHERWIN_SCRIPTS#80]
用户:【XXXXXX】登陆成功
>>>>>>开始执行签到
今日已签到，本周累计签到【3】天
>>>>>>超值福利签到
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 1750, in <module>
    run_result = RUN(infos, index).main()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 1594, in main
    self.superWelfare_receiveRedPacket()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/SFSY.py", line 172, in superWelfare_receiveRedPacket
    gift_names = ', '.join([gift['giftName'] for gift in gift_list])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Anthoney** [comment]
打开编辑器sfsy.py
找到这一行，前面加个#， 看了下小程序里，活动好像下线了
```python
#self.superWelfare_receiveRedPacket()
```

**Comment by Cyber-H** [comment]
确认成功，感谢感谢~~
